name: publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish
        run: ./build.cmd test publish
        env:
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
